### ISSUE TITLE
Pump timeout error on custom ethereum chain

### ISSUE THREAD

**Issue by Jonybang** [cybercongress/cyber-search#147]
Timeout error in pump module when trying to run demo with custom ethereum chain in parity container.

Docker compose config:
https://github.com/kenigtech/node/blob/master/cyber-node/docker-compose.yml

Parity logs (no errors):
https://pastebin.com/PLhtRdjd

Pump logs (timeout error):
https://pastebin.com/utFWhdyh

Grafana logs (no errors):
https://pastebin.com/2LvvP5vx

Curl output:
```
$ curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true],"id":1}' http://127.0.0.1:3945

{"jsonrpc":"2.0","result":{"author":"0xa17498232e4d02aacb68c6c4753706821c216fb6","difficulty":"0xffffffffffffffffffffffffede3a7d7","extraData":"0xd5830109038650617269747986312e32342e30826c69","gasLimit":"0x663be0","gasUsed":"0x0","hash":"0x9d7afcba19a0630719e9387b44738f86e49e0b9800fe35a4e0ad5d1f26b14de1","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0xa17498232e4d02aacb68c6c4753706821c216fb6","number":"0x1","parentHash":"0x74e97186bf3d0585cf6b4239220f743bc277b61ba453ccf237cb4c37d8b58444","receiptsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","sealFields":["0x84121c5828","0xb841644bc7501b7d16076d249a40000e2082f9a322a66aac99bd3b94a70ab77011a062c8742e281389c0783adf8c31a3d6855b5f85e3b660f7bea9f070187a18e39b00"],"sha3Uncles":"0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347","signature":"644bc7501b7d16076d249a40000e2082f9a322a66aac99bd3b94a70ab77011a062c8742e281389c0783adf8c31a3d6855b5f85e3b660f7bea9f070187a18e39b00","size":"0x240","stateRoot":"0xbe5db32bb8d77f9939d9b58903862bf9d029d1acbd3fb8568e084f6bc247d516","step":"303847464","timestamp":"0x5a8db8c8","totalDifficulty":"0xffffffffffffffffffffffffede5a7d7","transactions":[],"transactionsRoot":"0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421","uncles":[]},"id":1}
```

**Comment by arturalbov** [comment]
Hi @Jonybang ! Looks like pump doesn't see kafka. Seems that you've missed some ports in fast-data-dev image configuration.
Here how it should look:
```
 fast-data-dev:
    container_name: fast-data-dev-search
    image: landoop/fast-data-dev:latest
    ports:
      - "3030:3030"
      - "9092:9092"
      - "2181:2181"
      - "9581-9584:9581-9584"
    environment:
      RUNTESTS: 0
      SAMPLEDATA: 0
      FORWARDLOGS: 0
      ADV_HOST: 127.0.0.1
```
